- name: Download neovim v0.11.0
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.11.0/nvim-macos-arm64.tar.gz
    dest: /tmp/nvim-macos-arm64.tar.gz

- name: Extract neovim tarball
  ansible.builtin.shell: |
    tar -xzf /tmp/nvim-macos-arm64.tar.gz -C /tmp/

- name: Move nvim to /usr/local
  become: yes
  ansible.builtin.shell: |
    cp -rX /tmp/nvim-macos-arm64/. /usr/local/

- name: Cleanup nvim tarball
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/nvim-macos-arm64.tar.gz
    - /tmp/nvim-macos-arm64
