- name: Check Xcode Command Line Tools
  stat:
    path: /usr/bin/xcode-select
  register: xcode_check

- name: Install Xcode Command Line Tools
  command: xcode-select --install
  when: xcode_check.rc != 0

- name: Install required dependencies for nvim
  become: yes
  ansible.builtin.homebrew:
    name:
      - ninja
      - cmake
      - gettext
      - curl
    state: present

- name: Build nvim
  become: yes
  ansible.builtin.shell: |
    cd /tmp/neovim
    make CMAKE_BUILD_TYPE=RelWithDebInfo
    make install

    rm -rf /tmp/neovim
