- name: Tap the nikitabobko/tap repository
  homebrew_tap:
    name: nikitabobko/tap
    state: present

- name: Install Aerospace cask
  homebrew_cask:
    name: aerospace
    state: present

- name: Copy Aerospace config
  ansible.builtin.copy:
    src: "configs/osx/aerospace.toml"
    dest: "~/.aerospace.toml"
    mode: '0664'
