[window]
startup_mode = "Fullscreen"

[font.normal]
family = "Hack Nerd Font"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "Key1"
mods = "Alt"
  [keyboard.bindings.command]
  program = "/usr/bin/tmux"
  args = [ "select-window", "-t", "1"]

[[keyboard.bindings]]
key = "Key2"
mods = "Alt"
  [keyboard.bindings.command]
  program = "/usr/bin/tmux"
  args = [ "select-window", "-t", "2"]

[[keyboard.bindings]]
key = "Key3"
mods = "Alt"
  [keyboard.bindings.command]
  program = "/usr/bin/tmux"
  args = [ "select-window", "-t", "3"]

[[keyboard.bindings]]
key = "Key4"
mods = "Alt"
  [keyboard.bindings.command]
  program = "/usr/bin/tmux"
  args = [ "select-window", "-t", "4"]

[[keyboard.bindings]]
key = "Key5"
mods = "Alt"
  [keyboard.bindings.command]
  program = "/usr/bin/tmux"
  args = [ "select-window", "-t", "5"]

[[keyboard.bindings]]
key = "Key6"
mods = "Alt"
  [keyboard.bindings.command]
  program = "/usr/bin/tmux"
  args = [ "select-window", "-t", "6"]

[[keyboard.bindings]]
key = "Key7"
mods = "Alt"
  [keyboard.bindings.command]
  program = "/usr/bin/tmux"
  args = [ "select-window", "-t", "7"]

[[keyboard.bindings]]
key = "Key8"
mods = "Alt"
  [keyboard.bindings.command]
  program = "/usr/bin/tmux"
  args = [ "select-window", "-t", "8"]

[[keyboard.bindings]]
key = "Key9"
mods = "Alt"
  [keyboard.bindings.command]
  program = "/usr/bin/tmux"
  args = [ "select-window", "-t", "9"]

[[keyboard.bindings]]
key = "Key0"
mods = "Alt"
  [keyboard.bindings.command]
  program = "/usr/bin/tmux"
  args = [ "select-window", "-t", "0"]

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Alt|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

