- name: ensure fonts directory
  become: yes
  file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory

- name: Hack exists
  become: yes
  shell: "ls {{ lookup('env', 'HOME') }}/.fonts | grep HackNerd"
  register: hack_exists
  ignore_errors: yes

- name: Download Hack
  when: hack_exists is failed
  become: yes
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Hack.tar.xz
    dest: "{{ lookup('env', 'HOME') }}/.fonts/"
    remote_src: yes
