- name: Install required dependencies for nvim
  become: yes
  ansible.builtin.apt:
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - ripgrep
      - build-essential
    state: present

- name: Build nvim
  become: yes
  ansible.builtin.shell: |
    cd /tmp/neovim
    make CMAKE_BUILD_TYPE=RelWithDebInfo
    make install

    rm -rf /tmp/neovim
