- name: Install required dependencies for nvim
  become: yes
  ansible.builtin.apt:
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - build-essential
    state: present

- name: Clone nvim repository
  become: yes
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim
    dest: /tmp/neovim
    depth: 1
    version: "release-0.9"

- name: Build nvim
  become: yes
  ansible.builtin.shell: |
    cd /tmp/neovim
    make CMAKE_BUILD_TYPE=RelWithDebInfo
    make install

    rm -rf /tmp/neovim
